Fix RHMI patching
RedHatQE/openshift-cluster-management-python-wrapper pull request #32
Opened 2023-04-24 14:59 UTC by rnetser

Add missing `.exists`

2023-04-27 08:55 UTC, omrirh commented
/lgtm

2023-05-02 09:04 UTC, myakove requested changes

2023-05-02 09:04 UTC, myakove commented on ocm_python_wrapper/cluster.py
> +        rhmi = RHMI(name="rhoam", namespace="redhat-rhoam-operator")
please define it before the forloop and reuse it.

2023-05-03 05:44 UTC, rnetser commented on ocm_python_wrapper/cluster.py
> +                    break
```
                func=lambda: RHMI(
                    name="rhoam", namespace="redhat-rhoam-operator"
                ),
                exceptions_dict=NOT_FOUND_ERROR_EXCEPTION_DICT,
            ):
                if sample and sample.exists:
                    return sample
```

and restore the original code

2023-05-03 07:35 UTC, myakove approved these changes

2023-05-03 08:11 UTC, rnetser commented on ocm_python_wrapper/cluster.py
>                  func=lambda: RHMI(name="rhoam", namespace="redhat-rhoam-operator"),
done

2023-05-03 08:14 UTC, myakove requested changes
:)

2023-05-03 08:14 UTC, myakove approved these changes

2023-05-03 08:58 UTC, oharan2 commented on ocm_python_wrapper/cluster.py
> +            _rhmi = RHMI(name="rhoam", namespace="redhat-rhoam-operator")
Patching now works, but this line fails with non-existence (trying to reach too early before resource created):
`ocp_resources.resource WARNING Couldn't find RHMI in integreatly.org api group`
`*** NotImplementedError: Couldn't find RHMI in integreatly.org api group`

2023-05-03 11:44 UTC, rnetser commented
/verified

2023-05-03 11:46 UTC, myakove approved these changes

2023-05-03 11:47 UTC, merged