Support install/uninstall addon via rosa cli
RedHatQE/openshift-cluster-management-python-wrapper pull request #39
Opened 2023-05-17 07:10 UTC by oharan2

Supports [#15 ](https://github.com/RedHatQE/ocp-addons-operators-cli/pull/15) which accept `rosa-cli` flag to indicate the ROSA cli directly for addon installation.
Changes made in [#2 ](https://github.com/RedHatQE/rosa-python-client/pull/2) are required for usage.

2023-05-17 08:55 UTC, rnetser requested changes

2023-05-17 08:55 UTC, rnetser commented on ocm_python_wrapper/cluster.py
> +            user_parameters (List) : User parameter input set with values.
`User parameter input set with values.` please rephrase; what does `set with values` mean?

2023-05-17 08:55 UTC, rnetser commented on ocm_python_wrapper/cluster.py
> +        Returns: Updated parameters (if default values updated) to provide for installation.
missing newline

2023-05-17 08:55 UTC, rnetser commented on ocm_python_wrapper/cluster.py
> +        Returns: Updated parameters (if default values updated) to provide for installation.
the function does not return anything

2023-05-17 08:55 UTC, rnetser commented on ocm_python_wrapper/cluster.py
> +            # Billing-model is relevant for installation
is it relevant to all addons installed via cli?

2023-05-17 08:55 UTC, rnetser commented on pyproject.toml
> +    "python-benedict",
not part of this pr

2023-05-17 16:20 UTC, omrirh commented on ocm_python_wrapper/cluster.py
> +        rosa_cli=False,
```suggestion
        rosa=False,
```

`run_action` passes `rosa` param to `install_addon` kwargs as shown [here](https://github.com/RedHatQE/ocp-addons-operators-cli/blob/85a0cbe9c9f054bed19b0f80ac51aa8632a5ed21/app/addon_cmds/commands.py#L16)

2023-05-18 10:02 UTC, myakove requested changes

2023-05-18 10:02 UTC, myakove commented on pyproject.toml
> +    "rosa-pyhon-client"
typo

2023-05-18 20:47 UTC, oharan2 commented
/verified

2023-05-21 08:37 UTC, rnetser approved these changes

2023-05-21 09:08 UTC, myakove approved these changes

2023-05-21 09:08 UTC, merged