Update _wait_for_rhoam
RedHatQE/openshift-cluster-management-python-wrapper pull request #67
Opened 2023-06-12 11:28 UTC by oharan2

Recent openshift-ci [rehearses](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/40151/rehearse-40151-periodic-ci-CSPI-QE-MSI-rhods-rhoam-addons-v4.13-rhods-rhoam-tests/1668156753423896576) failed twice with 
`ocp_resources.utils.TimeoutExpiredError: Timed Out: 300` while installing RHOAM addon with our sampler.

Changes:
1. Update logging to catch unexpected errors (in addition to the one that's covered by the sampler)
2. Update timeout to be 15 minutes

2023-06-12 12:10 UTC, omrirh submitted a review, later dismissed

2023-06-12 12:19 UTC, oharan2 commented
/verified

2023-06-12 12:39 UTC, myakove submitted a review, later dismissed

2023-06-12 13:18 UTC, rnetser requested changes

2023-06-12 13:18 UTC, rnetser commented on ocm_python_wrapper/cluster.py
> +                LOGGER.info(f"{rosa_sampler['out'] or ''}{rosa_sampler['err'] or ''}")
please remove this log

2023-06-13 07:04 UTC, myakove approved these changes

2023-06-15 07:25 UTC, myakove commented
@oharan2 is this still needed?

2023-06-25 07:18 UTC, oharan2 commented
Resolved in [#27](https://github.com/RedHatQE/rosa-python-client/pull/27) (The rosa-cli interactive mode is influencing this execution)

2023-06-25 07:18 UTC, closed without merging